version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: motorcycle_rental_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motorcycle_rental_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - motorcycle_rental_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: motorcycle_rental_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@motorcyclerental.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - motorcycle_rental_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: motorcycle_rental_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - motorcycle_rental_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  motorcycle_rental_network:
    driver: bridge